openapi: 3.0.0
info:
  title: Eterna
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8000
tags:
  - name: Blog
  - name: Categories
  - name: Users
  - name: Auth
  - name: Comments
paths:
  /api/posts:
    post:
      tags:
        - Blog
      summary: Blog
      requestBody:
        content: {}
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Blog
      summary: Blog List
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/posts/16:
    get:
      tags:
        - Blog
      summary: Blog id
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{token}}
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Blog
      summary: Blog
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{token}}
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/posts/3:
    put:
      tags:
        - Blog
      summary: Blog put
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: POPULER Text Edit
                content: Populer blog post
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{token}}
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/posts/featured:
    get:
      tags:
        - Blog
      summary: Blog Featured
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{token}}
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/categories/:
    post:
      tags:
        - Categories
      summary: Categories
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: JS
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/categories/11:
    put:
      tags:
        - Categories
      summary: Categories
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Router
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{token}}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Categories
      summary: Categories id
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{token}}
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/categories:
    get:
      tags:
        - Categories
      summary: Categories List
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{token}}
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/users:
    get:
      tags:
        - Users
      summary: Users
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{token}}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/users/3/role:
    put:
      tags:
        - Users
      summary: User Role
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                role: user
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{token}}
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/users/5:
    delete:
      tags:
        - Users
      summary: User
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{token}}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/register:
    post:
      tags:
        - Auth
      summary: Register User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                first_name: New
                last_name: User
                phone: '51710013367'
                email: user@test.com
                password: '123456'
                role: user
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/login:
    post:
      tags:
        - Auth
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                login: admin@admin.com
                password: '123456'
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/logout:
    post:
      tags:
        - Auth
      summary: Logout
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                login: admin@admin.com
                password: '123456'
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{token}}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/posts/2/comments:
    post:
      tags:
        - Comments
      summary: Blog id Comments
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                content: Nice post!
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{token}}
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Comments
      summary: id Comments List
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{token}}
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/comments/40/approve:
    patch:
      tags:
        - Comments
      summary: Approve Comment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: ''
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{token}}
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/comments/42:
    delete:
      tags:
        - Comments
      summary: Comment
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{token}}
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
